---
title: 'Assignment 1'
author: "Data Science for Biomedical Informatics (BMIN503/EPID600)"
output:
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
    
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```    
***

### Instructions
- Download the Rmd version of this file
- Complete the questions below in RStudio using the Rmd file as a template 
- Replace text in brackets with your answers. Do not keep the brackets.
- Save the Rmd document as Assignment1_*YOUR LAST NAME*.Rmd
- Create an HTML version using knitr
- Turn in completed Assignment1_*YOUR LAST NAME*.html file in Canvas under Assignments -> Assignment 1
- Your assignment **must** be in html format or it will not be graded
- Grades will be assigned according to point scheme below and computed as a percentage of total possible points
- Lateness policy: If an urgent and unforseen circumstance comes up and you need an extension to turn in an assignment, please contact Blanca, Erin, and/or Emma as soon as possible. Unless there is an arrangement in place, late assignments will be scored as follows: 
    - 25% of total score if 1 day late
    - 50% of total score if 2 days late
    - 75%  of total score if 3 days late
    - Assignment will not be graded if 4 or more days late
- DUE DATE: 9/5/19 11:59pm


### Questions

1) Provide your name. *(1 point)* 

    Jonathan Beus

2) Provide the graduate or educational program at Penn that you are part of. *(1 point)* 

     Certificate in Biomedical Informatics

3) Describe what research topic(s) interest you using 2-3 sentences. *(2 points)* 

    My major research interests are improving patient safety and provider efficiency through the use of the Electronic Health Record (EHR). Clinically, I am generally interested in improving the care of hospitalized children and, in particular, am interested in antimicrobial stewardship as well as the diagnosis and treatment of Kawasaki Disease.

4) What are you most interested in learning during this course? *(2 points)* 

    I am most interested in learning about machine learning and high performance computing. As I am primarily self taught in R, I am also interested in formalized instruction in R to make sure I am using best practices.

5) Provide a direct link in your html file to your GitHub account, such that clicking on your GitHub username will result in opening of your GitHub account. *(2 points)* 

    [beusj](https://raw.githubusercontent.com/beusj/BMIN_503_Assigments/master/1/Assignment1_Beus.html)







